lakalici/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 nu

from __future__ import (unicode_literals, absolute_import,
                        division, print_function)
import logging

from django.conf.urls import patterns, include, url
from django.contrib import admin
from manager import urls as manager_urls

logger = logging.getLogger(__name__)

urlpatterns = patterns(
    '',
    url(r'', include(manager_urls)),

    # authentication
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'}, name='logout'),

    url(r'^admin/', include(admin.site.urls)),
)

manager/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 nu

from __future__ import (unicode_literals, absolute_import,
                        division, print_function)

from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView

urlpatterns = patterns(
    '',

    # Android API
    url(r'^fondasms/?$', 'fondasms.views.fondasms_handler',
        {'handler_module': 'manager.fondasms_handlers',
         'send_automatic_reply': False,
         'automatic_reply_via_handler': False,
         'automatic_reply_text': None},
        name='fondasms'),
    url(r'^fondasms/test/?$',
        TemplateView.as_view(template_name="fondasms_tester.html"),
        name='fondasms_tester'),

    url(r'^/?$', 'manager.views.about', name='about'),
    url(r'^groups/?$', 'manager.views.groups', name='groups'),
    url(r'^groups/(?P<slug>[a-zA-Z0-9\-]+)/?$',
        'manager.views.group_detail', name='group'),
    url(r'^groups/(?P<slug>[a-zA-Z0-9\-]+)/remove/(?P<contact_id>[0-9]+)/?$',
        'manager.views.group_contact_remove', name='group_contact_remove'),
    url(r'^groups/(?P<slug>[a-zA-Z0-9\-]+)/remove/?$',
        'manager.views.group_remove', name='group_delete'),
    url(r'^account/?$', 'manager.views.account', name='account'),
    url(r'^contacts/?$', 'manager.views.contacts', name='contacts'),
    url(r'^contacts/import/?$', 'manager.views.import_contacts',
        name='import_contacts'),
    url(r'^tasks/?$', 'manager.views.tasks', name='tasks'),
    url(r'^tasks/new/?$', 'manager.views.new_task', name='new_task'),
    url(r'^tasks/(?P<uid>[a-zA-Z0-9]+)/?$',
        'manager.views.task_detail', name='task'),

    url(r'^api/tasks/(?P<uid>[a-zA-Z0-9]+)/?$',
        'manager.views.api_task', name='api_task'),
    url(r'^api/tasks/(?P<uid>[a-zA-Z0-9]+)/update/?$',
        'manager.views.api_task_update', name='api_task_update'),
    url(r'^api/items/(?P<item_id>[a-zA-Z0-9]+)/update?$',
        'manager.views.api_item_update', name='api_item_update'),
)

manager/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 nu

from __future__ import (unicode_literals, absolute_import,
                        division, print_function)
import logging
import re
# import uuid
import random

from django.utils import timezone
from django.db import models
from django.db.models.signals import pre_save
from django.template.defaultfilters import slugify
from django.dispatch import receiver
from django.contrib.auth.models import (AbstractBaseUser,
                                        PermissionsMixin,
                                        UserManager)
from django.core import validators
from django.utils.translation import ugettext_lazy as _
from py3compat import implements_to_string

from manager.numbers import operator_from_malinumber, phonenumber_repr

logger = logging.getLogger(__name__)


def get_task_uuid():
    return Task.gen_uuid()


@implements_to_string
class Organization(models.Model):

    slug = models.SlugField()
    name = models.CharField(max_length=100)
    balance = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def to_dict(self, with_balance=False):
        d = {
            'slug': self.slug,
            'name': self.name
        }
        if with_balance:
            d.update({'balance': self.balance})
        return d


@implements_to_string
class Contact(models.Model):
    ORANGE = 'orange'
    MALITEL = 'malitel'
    UNKNOWN = 'unknown'
    FOREIGN = 'foreign'

    OPERATORS = {
        ORANGE: "Orange Mali",
        MALITEL: "Malitel",
        FOREIGN: "Étranger",
        UNKNOWN: "Inconnu"
    }

    class Meta:
        unique_together = ['number', 'organization']

    name = models.CharField(
        verbose_name="Name",
        max_length=500, blank=True, null=True)
    number = models.CharField(
        verbose_name="Phone Number",
        max_length=100, unique=True)
    operator = models.CharField(
        verbose_name="Operator",
        max_length=50, choices=OPERATORS.items(), default=UNKNOWN)
    organization = models.ForeignKey(
        Organization, verbose_name="Organization",
        related_name='contacts')

    def __str__(self):
        return self.name if self.name else phonenumber_repr(self.number)

    def to_dict(self, with_organization=False):
        d = {
            'id': self.id,
            'name': self.name,
            'number': self.number,
            'number_str': phonenumber_repr(self.number),
            'operator': self.operator
        }
        if with_organization:
            d.update({'organization': self.organization.to_dict()})
        return d

    @classmethod
    def get_or_none(cls, cid):
        try:
            return cls.objects.get(id=cid)
        except cls.DoesNotExist:
            return None


@receiver(pre_save, sender=Contact)
def pre_save_update_contact_operator(sender, instance, **kwargs):
    instance.operator = operator_from_malinumber(instance.number)


@implements_to_string
class Group(models.Model):

    slug = models.SlugField()
    name = models.CharField(max_length=150)
    members = models.ManyToManyField(Contact, related_name='groups')
    organization = models.ForeignKey(Organization, related_name='groups')

    def __str__(self):
        return self.name

    @classmethod
    def get_or_none(cls, slug):
        try:
            return cls.objects.get(slug=slug)
        except cls.DoesNotExist:
            return None


@receiver(pre_save, sender=Group)
def iter_pre_save_handler(sender, instance, **kwargs):
    if not instance.pk:
        instance.slug = slugify(instance.name)


@implements_to_string
class Task(models.Model):

    CREATED = 'created'
    PENDING = 'pending'
    PROCESSING = 'processing'
    COMPLETE = 'complete'

    STATUSES = {
        CREATED: "Created",
        PENDING: "Pending",
        PROCESSING: "Processing",
        COMPLETE: "Complete"
    }

    AIRTIME = 'airtime'
    MPAYMENT = 'mpayment'
    ACTIONS = {
        AIRTIME: "Crédit mobile",
        MPAYMENT: "mPayment"
    }

    uid = models.CharField(max_length=50,
                           primary_key=True,
                           default=get_task_uuid)
    organization = models.ForeignKey(Organization, related_name='tasks')
    action = models.CharField(
        max_length=50, choices=ACTIONS.items(), default=AIRTIME)
    name = models.CharField(max_length=150)
    status = models.SlugField(choices=STATUSES.items(),
                              default=CREATED)

    def __str__(self):
        return self.name

    def to_dict(self, with_organization=False):
        d = {
            'id': self.uid,
            'name': self.name,
            'status': self.status,
            'action': self.action,
            'total_amount': self.total_amount(),
        }
        if with_organization:
            d.update({'organization': self.organization.to_dict()})
        return d

    @classmethod
    def gen_uuid(cls):
        # _gen = lambda: uuid.uuid4().hex[:6].upper()
        _gen = lambda: str(random.randint(100000, 999999)).zfill(6)
        uid = _gen()
        while cls.objects.filter(uid=uid).count():
            uid = _gen
        return uid

    @classmethod
    def get_or_none(cls, uid):
        try:
            return cls.objects.get(uid=uid)
        except cls.DoesNotExist:
            return None

    def total_amount(self):
        return sum([ti.amount for ti in self.task_items.all()])

    def contacts(self):
        return [ti.contact for ti in self.task_items.all()]


@receiver(pre_save, sender=Task)
def pre_save_set_name_if_none(sender, instance, **kwargs):
    if instance.name is None:
        instance.name = instance.uid


@implements_to_string
class TaskItem(models.Model):

    CREATED = 'created'
    PENDING = 'pending'
    PROCESSING = 'processing'
    COMPLETE = 'complete'

    STATUSES = {
        CREATED: "Created",
        PENDING: "Pending",
        PROCESSING: "Processing",
        COMPLETE: "Complete"
    }

    class Meta:
        unique_together = ['task', 'contact']

    task = models.ForeignKey(Task, related_name='task_items')
    contact = models.ForeignKey(Contact, related_name='task_items')
    amount = models.PositiveIntegerField(default=0)
    status = models.SlugField(choices=STATUSES.items(), default=CREATED)
    receipt = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return "{amount} -> {contact}".format(
            amount=self.amount, contact=self.contact)

    @classmethod
    def get_or_none(cls, ti_id):
        try:
            return cls.objects.get(id=ti_id)
        except cls.DoesNotExist:
            return None

    def to_dict(self, with_task=True):
        d = {
            'id': self.id,
            'contact': self.contact.to_dict(),
            'amount': self.amount,
            'status': self.status
        }
        if with_task:
            d.update({'task': self.task.to_dict()})
        return d


@implements_to_string
class User(AbstractBaseUser, PermissionsMixin):

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    username = models.CharField(
        _("username"), max_length=50, primary_key=True,
        help_text=_("Required. 50 characters or fewer. "
                    "Letters, numbers and @/./+/-/_ characters"),
        validators=[validators.RegexValidator(re.compile("^[\w.@+-]+$"),
                    _("Enter a valid username."), "invalid")])

    first_name = models.CharField(max_length=100, blank=True, null=True,
                                  verbose_name=_("First Name"))
    last_name = models.CharField(max_length=100, blank=True, null=True,
                                 verbose_name=_("Last Name"))

    email = models.EmailField(_("email address"), blank=True, null=True)
    is_staff = models.BooleanField(
        _("staff status"), default=False,
        help_text=_("Designates whether the user can "
                    "log into this admin site."))
    is_active = models.BooleanField(
        _("active"), default=True,
        help_text=_("Designates whether this user should be treated as "
                    "active. Unselect this instead of deleting accounts."))
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    organization = models.ForeignKey(
        Organization, related_name='users', blank=True, null=True)

    objects = UserManager()

    def __str__(self):
        return self.name()

    def get_short_name(self):
        return self.name()

    def name(self):
        if not self.first_name and not self.last_name:
            return self.username
        elif not self.first_name:
            return self.last_name
        else:
            return self.first_name

    @classmethod
    def get_or_none(cls, username, with_inactive=False):
        qs = cls.objects if with_inactive else cls.active
        try:
            return qs.get(username=username)
        except cls.DoesNotExist:
            return None


class SMSMessage(models.Model):

    class Meta:
        verbose_name = _("SMS Message")
        verbose_name_plural = _("SMS Messages")

    INCOMING = 'incoming'
    OUTGOING = 'outgoing'
    DIRECTIONS = {
        INCOMING: _("Incoming"),
        OUTGOING: _("Outgoing")
    }

    SUCCESS = 'success'
    FAILURE = 'failure'
    BUFFERED = 'buffered'
    SMSC_SUBMIT = 'smsc_submit'
    SMSC_REJECT = 'smsc_reject'
    SMSC_NOTIFS = 'smsc_notifications'
    UNKNOWN = 'unknown'

    DELIVERY_STATUSES = {
        UNKNOWN: "Unknown",
        SUCCESS: "Delivery Success",
        FAILURE: "Delivery Failure",
        BUFFERED: "Message Buffered",
        SMSC_SUBMIT: "SMSC Submit",
        SMSC_REJECT: "SMSC Reject",
        SMSC_NOTIFS: "SMSC Intermediate Notifications",
    }

    direction = models.CharField(max_length=75,
                                 choices=DIRECTIONS.items())
    identity = models.CharField(max_length=100)

manager/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 nu

from __future__ import (unicode_literals, absolute_import,
                        division, print_function)
import logging

from django import forms
# import floppyforms.__future__ as forms

# from manager.models import Contact
from manager.numbers import normalized_phonenumber

logger = logging.getLogger(__name__)


class AddGroupForm(forms.Form):

    name = forms.CharField(
        label="Nom du groupe",
        required=True,
        widget=forms.TextInput(attrs={'placeholder': "Nom du groupe"}))


class AddSingleContact(forms.Form):

    number = forms.CharField(
        max_length=75,
        required=True,
        label="Number",
        help_text="If not a Mali number, use +indicator syntax.")

    name = forms.CharField(max_length=500, required=False)

    def clean_number(self):
        numbersent = self.cleaned_data.get('number')
        normalized = normalized_phonenumber(numbersent)
        if normalized is None:
            raise forms.ValidationError("Invalid Phone Number: %(value)s",
                                        code='invalid',
                                        params={'value': numbersent})
        return normalized


class ImportContactsFile(forms.Form):

    ACTIONS = {
        'create_group': "Créer un nouveau groupe",
        'add_to_group': "Ajouter au groupe",
        'reset_group': "Remplacer le groupe"
    }

    xls_file = forms.FileField(required=True, label="Fichier Excel")
    action = forms.ChoiceField(required=True, label="Destination")
    group = forms.ChoiceField(required=False, label="Groupe")
    group_name = forms.CharField(required=False, label="Nouveau groupe")

    def __init__(self, *args, **kwargs):
        organization = kwargs.pop('organization')
        super(ImportContactsFile, self).__init__(*args, **kwargs)

        self.fields['action'].choices = self.ACTIONS.items()
        self.fields['group'].choices = [
            (g.slug, g.name) for g in organization.groups.all()]

manager/templates/about.html
{% extends "base.html" %}

{% block content %}
<h1>Envoi de crédit en masse !</h1>

<p>LKLC est un service d'envoi automatisé de crédit téléphonique ainsi que de mpayment au Mali.</p>

<h2>À quoi sert <em>lakali ci</em> ?</h2>
<p>Si vous souhaitez envoyer du crédit téléphonique à plus de 10 personnes à la fois, le faire à la main (via les systèmes <em>mugan-mugan</em> ou <em>paani</em>) est <strong>très fastidieux</strong>.</p>
<p>Avec LKLC, il vous suffit de renseigner une fois les contacts de ces personnes (via un fichier Excel si la liste est longue) dans le système, de sélectionner le montant à envoyer et presser un bouton. Tout le reste est automatique!</p>
<p>En plus, vous pouvez suivre l'envoi et vérifier que les transferts ont été effectués correctement via les numéros de reçus.</p>

<h2>Et pour le mPayment</h2>
<p>De la même manière, vous pouvez envoyer du crédit <em>Orange Money</em> ou <em>Mobi Cash</em> à vos contacts, avec la même simplicité !</p>

<h2>Convaincu ?</h2>
<p>Pour profiter de LKLC, merci de renseigner votre adresse email ci-dessous, nous vou
{% endblock %}

manager/templates/account.html
{% extends "base.html" %}

{% block content %}
<h2>Rechargez votre compte !</h2>
<p>Pour recharger votre compte, envoyez la somme désirée via Orange Money au numéro <strong>73 12 08 96</strong> et patientez une quinzaine de minutes pour l'actualisation de votre solde.</p>

<p>En cas de problème, veuillez contacter le XX XX XX XX.</p>
{% endblock %}

manager/templates/add_single_contact.html
<form class="add_single_contact pure-form" method="POST">
    <fieldset>
        <legend>Ajouter un contact</legend>
        <input type="number" placeholder="Numéro">
        <input type="text" placeholder="Nom (facultatif)">
        <button type="submit" class="pure-button pure-button-primary">Ajouter</button>
    </fieldset>
</form>

manager/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>lakali ci!</title>
	<link rel="stylesheet" href="{% static 'pure.min.css' %}">
	<link rel="stylesheet" href="{% static 'ci.css' %}">
	<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	<div class="pure-g">
  		<div class="pure-u-1-5 sidebar">	    
		    <div class="pure-menu pure-menu-open">
			    {% if user.is_authenticated %}<span class="pure-menu-heading"><i class="fa fa-send"></i> {{ user.organization|default:"ADMIN" }}</span>
			    {% else %}<a class="pure-menu-heading">lakali ci!</a>{% endif %}

			    <ul>
			       	<li class="{% if domain = 'about' %}pure-menu-selected {% endif %}"><a href="{% url 'about' %}"><i class="fa fa-home"></i> Accueil</a></li>
			       	<li class="{% if domain = 'account' %}pure-menu-selected {% endif %}"><a href="{% url 'account' %}"><i class="fa fa-user"></i> Mon Compte <span class="count">({{ account_balance}}F)</span></a></li>
			       	<li class="{% if domain = 'tasks' %}pure-menu-selected {% endif %}"><a href="{% url 'tasks' %}"><i class="fa fa-tasks"></i> Tâches <span class="count">({{ tasks.count }})</span></a></li>
			        <li class="{% if domain = 'contacts' %}pure-menu-selected {% endif %}"><a href="{% url 'contacts' %}"><i class="fa fa-users"></i> Contacts <span class="count">({{ contacts.count }})</span></a></li>
			        <li class="{% if domain = 'groups' %}pure-menu-selected {% endif %}"><a href="{% url 'groups' %}"><i class="fa fa-folder-open-o"></i> Groupes</a></li>
			        {% for group in groups.all %}
			        	<li class="{% if domain = 'groups' %}pure-menu-selected {% endif %}"><a href="{% url 'group' group.slug %}">&nbsp;&nbsp;&nbsp;<i class="fa fa-chevron-right"></i> {{ group.name }} <span class="count">({{ group.members.count }})</span></a></li>
			        {% endfor %}
			        {% if user.is_authenticated %}<li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Déconnection <em>{{ user.name }}</em></a></li>{% endif %}
			    </ul>
			</div>

		    <ul>
		        
		    </ul>
		</div>

  		<div class="pure-u-4-5 content">
  			{% if messages %}
                <div id="notifications" class="">
                {% for message in messages %}
                    <p class="alert alert-{% if message.tags == 'error'%}danger{% else %}{{ message.tags }}{% endif %}">{{ message }}<i class="icon-cancel close-notif-button"></i></p>
                {% endfor %}
                </div>
            {% endif %}
		    {% block content %}
			{% endblock %}
  		</div>

  	</div>
    <script src="{% static 'jquery-1.11.min.js' %}"></script>
    <script type="text/javascript">
    $(document).ready(function () {
    	{% block onJQstart %}{% endblock %}
    });
    </script>
  </body>
</html>

manager/templates/contacts.html
{% extends "base.html" %}

{% block content %}
{% include "add_single_contact.html" %}
<a class="pure-button" href="{% url 'import_contacts' %}">Importer des contacts</a>

<h1>Contacts</h1>
{% for contact in contacts.all %}
{% if forloop.first %}<ul>{% endif %}
<li>{{ contact }}</li>
{% if forloop.last %}</ul>{% endif %}
{% empty %}
<p>Pas de contact pour le moment.</p>
{% endfor %}
{% endblock %}

manager/templates/group.html
{% extends "base.html" %}
{% load lklc %}

{% block content %}
<h1>{{ group.name }}</h1>

<form class="new-contact-form pure-form pure-form-stacked" method="POST">
{% csrf_token %}
    <fieldset>
        <legend>Ajouter un contact</legend>
		{{ form.as_p }}
		<button type="submit" class="pure-button pure-button-primary">Ajouter</button>
    </fieldset>
</form>

<p>
	<button class="create-task pure-button button-secondary">
	<i class="fa fa-plus"></i> Créer une tâche avec ces <span id="nb_selected_contacts">0</span> contacts</button>
	<a href="{% url 'group_delete' group.slug %}" class="pure-button button-error">
	<i class="fa fa-trash"></i> Supprimer le groupe</a>
</p>

{% for contact in group.members.all %}
{% if forloop.first %}
<form id="create-task-form" method="POST" action="{% url 'new_task' %}">
{% csrf_token %}
<table class="contact-table pure-table pure-table-bordered pure-table-striped">
<thead>
<tr>
	<th><input type="checkbox" id="select_all" value="true" /></th>
	<th>Numéro</th>
	<th>Nom</th>
	<th>Opérateur</th>
	<th><i title="Retirer du groupe" class="fa fa-trash"></i></th>
</tr>
</thead>
<tbody>
{% endif %}
<tr>
	<td><input type="checkbox" name="contact_ids" value="{{ contact.id }}" /></td>
	<td>{{ contact.number|phone }}</td>
	<td>{{ contact.name }}</td>
	<td>{{ contact.operator|carrier }}</td>
	<td><a href="{% url 'group_contact_remove' group.slug contact.id %}"><i class="fa fa-trash"></i></a></td>
</tr>
{% if forloop.last %}
</tbody>
</table>
</form>
{% endif %}
{% empty %}
<p>Pas de contact dans ce groupe !</p>
{% endfor %}
{% endblock %}

{% block onJQstart %}
var all_boxes = $('.contact-table tbody input');
$('#select_all').on('change', function (e) {
	var is_checked = ($(this).prop('checked') === true);
	if (is_checked) {
		all_boxes.prop('checked', true);
	} else {
		all_boxes.prop('checked', false);
	}
	console.log(all_boxes);
});

function disable_button(selector) {
	selector.addClass('pure-button-disabled');
	selector.prop('disabled', true);
}

function enable_button(selector) {
	selector.removeClass('pure-button-disabled');
	selector.prop('disabled', false);	
}

// update button number
function update_nb_selected() {
	var nb = $('.contact-table tbody input:checked').length;
	$('#nb_selected_contacts').text(nb);
	var btn = $('.create-task');
	if (nb == 0) {
		disable_button(btn);
	} else {
		enable_button(btn)
	}
}
$('input[type=checkbox]').on('change', update_nb_selected);
update_nb_selected();

$('.create-task').on('click', function (e) {
	$('#create-task-form').submit();	
});
{% endblock %}

manager/templates/groups.html
{% extends "base.html" %}

{% block content %}
<h2>Ajouter un groupe</h2>
<form class="add_single_group pure-form" method="POST">
{% csrf_token %}
	<p>Notez que vous pouvez créer automatiquement vos groupes lors de l'<a href="{% url 'import_contacts' %}">import de vos contacts</a>.</p>
    <fieldset>
    	{% if form.errors.name %}
    	<p class="error"><i class="fa fa-exclamation-triangle"></i> {{ form.errors.name.0 }}</p>{% endif %}
        {{ form.name }}
        <button type="submit" class="pure-button pure-button-primary">Ajouter</button>
    </fieldset>
</form>
{% endblock %}

manager/templates/import_contacts.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<h1>Importer des contacts</h1>
<p>Ici, vous pouvez importer un grand nombre de contact d'un coup, sans avoir à le faire un à un.</p>
<p>LKLC n'enregistre que deux informations pour un contact : <strong>le numéro de téléphone</strong> et <strong>le nom</strong> (facultatif).</p>

<form class="import_contacts pure-form pure-form-stacked" method="POST" enctype="multipart/form-data">
{% csrf_token %}
	<legend>Importer votre fichier de contacts <i class="fa fa-file-excel-o"></i></legend>
    <fieldset>
        <p>En utilisant notre <a href="{% static 'contacts-lklc.xls' %}">modèle Excel</a>, vous pouvez simplement copier-coller tous vos contacts et les importer en un clic.</p>
        {{ form.as_p }}
        <button type="submit" class="pure-button pure-button-primary">Importer le fichier</button>
    </fieldset>
</form>

{% endblock %}

{% block onJQstart %}
var group_container = $("#id_group").parent();
var group_name_container = $("#id_group_name").parent();
function toggle_group_list_name(val) {
	if (val == 'add_to_group' || val == 'reset_group') {
		group_container.show();
		group_name_container.hide();
	} else {
		group_container.hide();
		group_name_container.show();
	}
}
$("#id_action").on('change', function (e) {
	toggle_group_list_name($(this).val());
});
toggle_group_list_name($("#id_action").val());
{% endblock %}

manager/templates/login.html
{% extends "base.html" %}

{% block title %}Identification{% endblock %}

{% block content %}

<h1>Identification</h1>

{% if form.errors %}
<p class="alert alert-danger">Votre nom d'utilisateur et mot de passe ne correspondent pas. S'il vous plaît essayez de nouveau.</p>
{% endif %}

<p class="alert alert-warning">En cas de perte de votre identifiant ou mot de passe, appellez la Hotline au <strong>76 49 90 55</strong>.</p>

<form class="pure-form" method="POST">
    {% csrf_token %}
    <fieldset>
        <legend>Merci de vous identifier</legend>

        <input type="text" name="{{ form.username.name }}"
               placeholder="{{ form.username.label }}"
               autofocus="autofocus">
        <input type="password" name="{{ form.password.name }}"
               placeholder="{{ form.password.label }}">

        <button type="submit" class="pure-button pure-button-primary">S'identifier</button>
    </fieldset>
</form>
{% endblock %}

manager/templates/tasks.html
{% extends "base.html" %}

{% block content %}
<h1>Tâches</h1>
{% for task in tasks.all %}
{% if forloop.first %}
<table class="contact-table pure-table pure-table-bordered pure-table-striped">
<thead>
<tr>
	<th>ID</th>
	<th>Nom</th>
	<th>Action</th>
	<th>Nb éléments</th>
	<th>Montant total</th>
	<th>Statut</th>
	<th><i title="Retirer dde la tâche" class="fa fa-trash"></i></th>
</tr>
</thead>
<tbody>
{% endif %}
<tr>
	<td><a href="{% url 'task' task.uid %}">{{ task.uid }}</a></td>
	<td>{{ task.name }}</td>
	<td>{{ task.action }}</td>
	<td>{{ task.task_items.count }}</td>
	<td>{{ task.total_amount }}</td>
	<td>{{ task.status }}</td>
	<td><a href=""><i class="fa fa-trash"></i></a></td>
</tr>
{% if forloop.last %}
</tbody>
</table>
{% endif %}
{% empty %}
<p>Pas de tâche pour le moment !</p>
{% endfor %}
{% endblock %}